### ISSUE TITLE
Error with examples.roberta

### ISSUE THREAD

**Issue by chuhailinh** [Huffon/sentence-compressor#3]
I'm getting an error when I'm trying to preprocess by command bash preprocess.sh:
My error is:
/usr/bin/python3: Error while finding module specification for 'examples.roberta.multiprocessing_bpe_encoder' (ModuleNotFoundError: No module named 'examples.roberta')
/usr/bin/python3: Error while finding module specification for 'examples.roberta.multiprocessing_bpe_encoder' (ModuleNotFoundError: No module named 'examples.roberta')
/usr/bin/python3: Error while finding module specification for 'examples.roberta.multiprocessing_bpe_encoder' (ModuleNotFoundError: No module named 'examples.roberta')
/usr/bin/python3: Error while finding module specification for 'examples.roberta.multiprocessing_bpe_encoder' (ModuleNotFoundError: No module named 'examples.roberta')
Namespace(align_suffix=None, alignfile=None, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='data-bin', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='source', srcdict='dict.txt', target_lang='target', task='translation', tensorboard_logdir='', testpref=None, tgtdict='dict.txt', threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='data/train.bpe', user_dir=None, validpref='data/val.bpe', workers=60)
| [source] Dictionary: 50263 types
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-preprocess", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/preprocess.py", line 346, in cli_main
    main(args)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/preprocess.py", line 245, in main
    make_all(args.source_lang, src_dict)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/preprocess.py", line 227, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/preprocess.py", line 223, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/preprocess.py", line 109, in make_binary_dataset
    offsets = Binarizer.find_offsets(input_file, num_workers)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/binarizer.py", line 73, in find_offsets
    with open(filename, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.bpe.source'

Can anyone help me to fix it??

**Comment by licccc52** [comment]
I have the same question as you, did you fix it？

**Comment by chuhailinh** [comment]
the data doesn't seem to be decompressed, so I unzip data in folder file data and running this command
